[[PCL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5c5ed36e6782d33642a9b782f4c0fda41f235a6"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "6b81bce17e2ce7450965561af34bbbb52634464bd2862f67e5a7c052bb47fade"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PCL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8ced9c66e53c9dad27496709e0adfa89b9b3ec6"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "02cdf5df7243b2b55adee8c6cc6c06259b2ea2d1d778d6393df195782f320bff"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PCL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "155a4976d1b195d8c014e8c7ef3fd7d9b94405bc"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "248a327655aef8f7fc3d61919175d8f26e2ed030d4c89777b8a49b934c1f2bef"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.aarch64-linux-musl-cxx03.tar.gz"
[[PCL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33ae4096f5693a64878e712f694bb64adb96672f"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "c953cfe46acb34ba197199c784bc1716057adc62ac5e88c58c798750dd09478e"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[PCL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23c583e6175ea8916db37d4c8ce7ce47467e43c3"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "bced153d3ebe8c240e5b9ab897f9766725b9e1239f873611ba7dd03c33863181"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PCL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba2b4b2237b51067c6806c3acc441191171ddbb"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "d493474fb22a493bfbc33d4bd0e537ac4f96e76d360e2ffd298537094aa862ad"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PCL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3473a83e544c1b6de681af0d7c927cce38e74dcf"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "77f2bb1ce2ddbdd85d6f9cec54c9a2ea745af47e7e069f315edf0e70b5c9a857"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PCL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8fb1820370122fe5931db409f4c4b94354685e0"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "902c564b9b2081d8968c07a83127a5ca0ce1b846a45a0e59f1833cc73bea8bb8"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fa2f846b56319b8be24103c2f59e970ae24af5f"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "3357619aef9229512b01208fd5c920850a692f6150729e92ee29880112e76576"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-linux-gnu-cxx03.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "467ef35b508772a7cbdd56772b8989e1d6539311"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "52b36fb6be15fdf27ada202e4c1d4052680bdc32c70164cdb6a27fa7c92a1000"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-linux-gnu-cxx11.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adccdc67c47a65de70b5dad9fa9a6c18c8c3eee4"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "9434e45d179cd2273e8569b069c0265223fc58556019061ef8abf03607f96bdf"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-linux-musl-cxx03.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "519792e407f2cab637d3539fee12fc802e4f6990"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "32e9f68d6d9e339a646a133673fe499a626c6b7407a8bf4dfa9aec6b16f868fb"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-linux-musl-cxx11.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53e9ff1d7e47d76f4e366087738727c95dab0f6a"
os = "windows"

    [[PCL.download]]
    sha256 = "dcfd94a4e38acc407dc433062d586fcc5009fb1c4d72c92e9a3e0365add3494b"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-w64-mingw32-cxx03.tar.gz"
[[PCL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "343693a4e070ed89063686dedb0c36f1330a3a52"
os = "windows"

    [[PCL.download]]
    sha256 = "f6b822bd9bfb927a4630de24492291800c76d5b9da5b0f2e96eb51e4204259b4"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.i686-w64-mingw32-cxx11.tar.gz"
[[PCL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d830a5c347508dd0b42ce1611d766bd0fcefe292"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "a6302605964cdf735ac176551a8bf785c642f07d734706370c80badaca2db1c4"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PCL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d305a40fb5ee5bd58751bfcb02ad85cbe1049da8"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "2c80e240861da80ef0b1e4ba83e832f4511082e8751e01088363b0c06800485b"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PCL]]
arch = "x86_64"
git-tree-sha1 = "b192f3adf9ccf7ad6fdd24e5d522d6904a445580"
os = "macos"

    [[PCL.download]]
    sha256 = "bb1b587e1b66a3b7a3f63bdafa956d34acb8acda977f9468ca2346dd54bb116a"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-apple-darwin.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf187568ad36094bb40d9dbe17d081bcc33a48e3"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "0fcc0cd9762ab164e2dba0d663d77209ff92620b072e0585a2576f3eca7a9a73"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18003e3c6c0e38561771b72dc24ef971ab8b1912"
libc = "glibc"
os = "linux"

    [[PCL.download]]
    sha256 = "136995a72239cdca7eec13b01f61bff5914ceac8503596aea6f9f7355a4552a3"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aafe349ca0078ea5fcc2f4d9c2871d286a59a193"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "bbb67383a0a2a4e25dc78ce54a2cd27e0e92fb0709357713fc8d7aced6bc2b1b"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-linux-musl-cxx03.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06aa7ed14f4d0da45dd300c7c8030b843161e53f"
libc = "musl"
os = "linux"

    [[PCL.download]]
    sha256 = "f67f140a4ecce59a62685034ac77e51de6ef34ab9e3119dfdd53fdd26652cdb6"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[PCL]]
arch = "x86_64"
git-tree-sha1 = "84fab5c2b0541ef49a3237bfb0f655b11dcc5419"
os = "freebsd"

    [[PCL.download]]
    sha256 = "fb27e1f088ae24e56398b9d186f22a107bef528ee1550825742407829c383ab8"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-unknown-freebsd.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38c1a4df2034d1cd2f0ed4716f084ca507b24c5a"
os = "windows"

    [[PCL.download]]
    sha256 = "7f87586c576c3996d6fcaa830738b8b8a37e18b9334645c4ebed71d9c1309438"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PCL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f70506cd4651af7e7b9bf56c9fe4aa4aff43ab"
os = "windows"

    [[PCL.download]]
    sha256 = "d6215c6cf2f49b122051bab3688101ccf3c8e7f3b08fe97e9856984a38637c70"
    url = "https://github.com/JuliaBinaryWrappers/PCL_jll.jl/releases/download/PCL-v1.12.0+0/PCL.v1.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
