# Autogenerated wrapper script for PCL_jll for powerpc64le-linux-gnu-cxx03
export libpcl_common, libpcl_features, libpcl_filters, libpcl_io, libpcl_io_ply, libpcl_kdtree, libpcl_keypoints, libpcl_ml, libpcl_octree, libpcl_recognition, libpcl_registration, libpcl_sample_consensus, libpcl_search, libpcl_segmentation, libpcl_stereo, libpcl_surface, libpcl_tracking, pcl_add_gaussian_noise, pcl_boundary_estimation, pcl_cluster_extraction, pcl_compute_cloud_error, pcl_compute_hausdorff, pcl_concatenate_points_pcd, pcl_convert_pcd_ascii_binary, pcl_crf_segmentation, pcl_demean_cloud, pcl_elch, pcl_extract_feature, pcl_fast_bilateral_filter, pcl_fpfh_estimation, pcl_generate, pcl_gp3_surface, pcl_grid_min, pcl_hdl_grabber, pcl_icp, pcl_icp2d, pcl_linemod_detection, pcl_local_max, pcl_lum, pcl_marching_cubes_reconstruction, pcl_match_linemod_template, pcl_mls_smoothing, pcl_morph, pcl_ndt2d, pcl_ndt3d, pcl_normal_estimation, pcl_outlier_removal, pcl_passthrough_filter, pcl_pcd2ply, pcl_pcd2vtk, pcl_pcd_change_viewpoint, pcl_pcd_convert_NaN_nan, pcl_pcd_introduce_nan, pcl_pclzf2pcd, pcl_plane_projection, pcl_ply2obj, pcl_ply2pcd, pcl_ply2ply, pcl_ply2raw, pcl_plyheader, pcl_poisson_reconstruction, pcl_progressive_morphological_filter, pcl_radius_filter, pcl_sac_segmentation_plane, pcl_spin_estimation, pcl_train_linemod_template, pcl_train_unary_classifier, pcl_transform_from_viewpoint, pcl_transform_point_cloud, pcl_unary_classifier_segment, pcl_uniform_sampling, pcl_vfh_estimation, pcl_voxel_grid, pcl_xyz2pcd

using CompilerSupportLibraries_jll
using FLANN_jll
using boost_jll
using Eigen_jll
JLLWrappers.@generate_wrapper_header("PCL")
JLLWrappers.@declare_library_product(libpcl_common, "libpcl_common.so.1.12")
JLLWrappers.@declare_library_product(libpcl_features, "libpcl_features.so.1.12")
JLLWrappers.@declare_library_product(libpcl_filters, "libpcl_filters.so.1.12")
JLLWrappers.@declare_library_product(libpcl_io, "libpcl_io.so.1.12")
JLLWrappers.@declare_library_product(libpcl_io_ply, "libpcl_io_ply.so.1.12")
JLLWrappers.@declare_library_product(libpcl_kdtree, "libpcl_kdtree.so.1.12")
JLLWrappers.@declare_library_product(libpcl_keypoints, "libpcl_keypoints.so.1.12")
JLLWrappers.@declare_library_product(libpcl_ml, "libpcl_ml.so.1.12")
JLLWrappers.@declare_library_product(libpcl_octree, "libpcl_octree.so.1.12")
JLLWrappers.@declare_library_product(libpcl_recognition, "libpcl_recognition.so.1.12")
JLLWrappers.@declare_library_product(libpcl_registration, "libpcl_registration.so.1.12")
JLLWrappers.@declare_library_product(libpcl_sample_consensus, "libpcl_sample_consensus.so.1.12")
JLLWrappers.@declare_library_product(libpcl_search, "libpcl_search.so.1.12")
JLLWrappers.@declare_library_product(libpcl_segmentation, "libpcl_segmentation.so.1.12")
JLLWrappers.@declare_library_product(libpcl_stereo, "libpcl_stereo.so.1.12")
JLLWrappers.@declare_library_product(libpcl_surface, "libpcl_surface.so.1.12")
JLLWrappers.@declare_library_product(libpcl_tracking, "libpcl_tracking.so.1.12")
JLLWrappers.@declare_executable_product(pcl_add_gaussian_noise)
JLLWrappers.@declare_executable_product(pcl_boundary_estimation)
JLLWrappers.@declare_executable_product(pcl_cluster_extraction)
JLLWrappers.@declare_executable_product(pcl_compute_cloud_error)
JLLWrappers.@declare_executable_product(pcl_compute_hausdorff)
JLLWrappers.@declare_executable_product(pcl_concatenate_points_pcd)
JLLWrappers.@declare_executable_product(pcl_convert_pcd_ascii_binary)
JLLWrappers.@declare_executable_product(pcl_crf_segmentation)
JLLWrappers.@declare_executable_product(pcl_demean_cloud)
JLLWrappers.@declare_executable_product(pcl_elch)
JLLWrappers.@declare_executable_product(pcl_extract_feature)
JLLWrappers.@declare_executable_product(pcl_fast_bilateral_filter)
JLLWrappers.@declare_executable_product(pcl_fpfh_estimation)
JLLWrappers.@declare_executable_product(pcl_generate)
JLLWrappers.@declare_executable_product(pcl_gp3_surface)
JLLWrappers.@declare_executable_product(pcl_grid_min)
JLLWrappers.@declare_executable_product(pcl_hdl_grabber)
JLLWrappers.@declare_executable_product(pcl_icp)
JLLWrappers.@declare_executable_product(pcl_icp2d)
JLLWrappers.@declare_executable_product(pcl_linemod_detection)
JLLWrappers.@declare_executable_product(pcl_local_max)
JLLWrappers.@declare_executable_product(pcl_lum)
JLLWrappers.@declare_executable_product(pcl_marching_cubes_reconstruction)
JLLWrappers.@declare_executable_product(pcl_match_linemod_template)
JLLWrappers.@declare_executable_product(pcl_mls_smoothing)
JLLWrappers.@declare_executable_product(pcl_morph)
JLLWrappers.@declare_executable_product(pcl_ndt2d)
JLLWrappers.@declare_executable_product(pcl_ndt3d)
JLLWrappers.@declare_executable_product(pcl_normal_estimation)
JLLWrappers.@declare_executable_product(pcl_outlier_removal)
JLLWrappers.@declare_executable_product(pcl_passthrough_filter)
JLLWrappers.@declare_executable_product(pcl_pcd2ply)
JLLWrappers.@declare_executable_product(pcl_pcd2vtk)
JLLWrappers.@declare_executable_product(pcl_pcd_change_viewpoint)
JLLWrappers.@declare_executable_product(pcl_pcd_convert_NaN_nan)
JLLWrappers.@declare_executable_product(pcl_pcd_introduce_nan)
JLLWrappers.@declare_executable_product(pcl_pclzf2pcd)
JLLWrappers.@declare_executable_product(pcl_plane_projection)
JLLWrappers.@declare_executable_product(pcl_ply2obj)
JLLWrappers.@declare_executable_product(pcl_ply2pcd)
JLLWrappers.@declare_executable_product(pcl_ply2ply)
JLLWrappers.@declare_executable_product(pcl_ply2raw)
JLLWrappers.@declare_executable_product(pcl_plyheader)
JLLWrappers.@declare_executable_product(pcl_poisson_reconstruction)
JLLWrappers.@declare_executable_product(pcl_progressive_morphological_filter)
JLLWrappers.@declare_executable_product(pcl_radius_filter)
JLLWrappers.@declare_executable_product(pcl_sac_segmentation_plane)
JLLWrappers.@declare_executable_product(pcl_spin_estimation)
JLLWrappers.@declare_executable_product(pcl_train_linemod_template)
JLLWrappers.@declare_executable_product(pcl_train_unary_classifier)
JLLWrappers.@declare_executable_product(pcl_transform_from_viewpoint)
JLLWrappers.@declare_executable_product(pcl_transform_point_cloud)
JLLWrappers.@declare_executable_product(pcl_unary_classifier_segment)
JLLWrappers.@declare_executable_product(pcl_uniform_sampling)
JLLWrappers.@declare_executable_product(pcl_vfh_estimation)
JLLWrappers.@declare_executable_product(pcl_voxel_grid)
JLLWrappers.@declare_executable_product(pcl_xyz2pcd)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, FLANN_jll, boost_jll, Eigen_jll)
    JLLWrappers.@init_library_product(
        libpcl_common,
        "lib/libpcl_common.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_features,
        "lib/libpcl_features.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_filters,
        "lib/libpcl_filters.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_io,
        "lib/libpcl_io.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_io_ply,
        "lib/libpcl_io_ply.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_kdtree,
        "lib/libpcl_kdtree.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_keypoints,
        "lib/libpcl_keypoints.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_ml,
        "lib/libpcl_ml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_octree,
        "lib/libpcl_octree.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_recognition,
        "lib/libpcl_recognition.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_registration,
        "lib/libpcl_registration.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_sample_consensus,
        "lib/libpcl_sample_consensus.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_search,
        "lib/libpcl_search.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_segmentation,
        "lib/libpcl_segmentation.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_stereo,
        "lib/libpcl_stereo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_surface,
        "lib/libpcl_surface.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcl_tracking,
        "lib/libpcl_tracking.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        pcl_add_gaussian_noise,
        "bin/pcl_add_gaussian_noise",
    )

    JLLWrappers.@init_executable_product(
        pcl_boundary_estimation,
        "bin/pcl_boundary_estimation",
    )

    JLLWrappers.@init_executable_product(
        pcl_cluster_extraction,
        "bin/pcl_cluster_extraction",
    )

    JLLWrappers.@init_executable_product(
        pcl_compute_cloud_error,
        "bin/pcl_compute_cloud_error",
    )

    JLLWrappers.@init_executable_product(
        pcl_compute_hausdorff,
        "bin/pcl_compute_hausdorff",
    )

    JLLWrappers.@init_executable_product(
        pcl_concatenate_points_pcd,
        "bin/pcl_concatenate_points_pcd",
    )

    JLLWrappers.@init_executable_product(
        pcl_convert_pcd_ascii_binary,
        "bin/pcl_convert_pcd_ascii_binary",
    )

    JLLWrappers.@init_executable_product(
        pcl_crf_segmentation,
        "bin/pcl_crf_segmentation",
    )

    JLLWrappers.@init_executable_product(
        pcl_demean_cloud,
        "bin/pcl_demean_cloud",
    )

    JLLWrappers.@init_executable_product(
        pcl_elch,
        "bin/pcl_elch",
    )

    JLLWrappers.@init_executable_product(
        pcl_extract_feature,
        "bin/pcl_extract_feature",
    )

    JLLWrappers.@init_executable_product(
        pcl_fast_bilateral_filter,
        "bin/pcl_fast_bilateral_filter",
    )

    JLLWrappers.@init_executable_product(
        pcl_fpfh_estimation,
        "bin/pcl_fpfh_estimation",
    )

    JLLWrappers.@init_executable_product(
        pcl_generate,
        "bin/pcl_generate",
    )

    JLLWrappers.@init_executable_product(
        pcl_gp3_surface,
        "bin/pcl_gp3_surface",
    )

    JLLWrappers.@init_executable_product(
        pcl_grid_min,
        "bin/pcl_grid_min",
    )

    JLLWrappers.@init_executable_product(
        pcl_hdl_grabber,
        "bin/pcl_hdl_grabber",
    )

    JLLWrappers.@init_executable_product(
        pcl_icp,
        "bin/pcl_icp",
    )

    JLLWrappers.@init_executable_product(
        pcl_icp2d,
        "bin/pcl_icp2d",
    )

    JLLWrappers.@init_executable_product(
        pcl_linemod_detection,
        "bin/pcl_linemod_detection",
    )

    JLLWrappers.@init_executable_product(
        pcl_local_max,
        "bin/pcl_local_max",
    )

    JLLWrappers.@init_executable_product(
        pcl_lum,
        "bin/pcl_lum",
    )

    JLLWrappers.@init_executable_product(
        pcl_marching_cubes_reconstruction,
        "bin/pcl_marching_cubes_reconstruction",
    )

    JLLWrappers.@init_executable_product(
        pcl_match_linemod_template,
        "bin/pcl_match_linemod_template",
    )

    JLLWrappers.@init_executable_product(
        pcl_mls_smoothing,
        "bin/pcl_mls_smoothing",
    )

    JLLWrappers.@init_executable_product(
        pcl_morph,
        "bin/pcl_morph",
    )

    JLLWrappers.@init_executable_product(
        pcl_ndt2d,
        "bin/pcl_ndt2d",
    )

    JLLWrappers.@init_executable_product(
        pcl_ndt3d,
        "bin/pcl_ndt3d",
    )

    JLLWrappers.@init_executable_product(
        pcl_normal_estimation,
        "bin/pcl_normal_estimation",
    )

    JLLWrappers.@init_executable_product(
        pcl_outlier_removal,
        "bin/pcl_outlier_removal",
    )

    JLLWrappers.@init_executable_product(
        pcl_passthrough_filter,
        "bin/pcl_passthrough_filter",
    )

    JLLWrappers.@init_executable_product(
        pcl_pcd2ply,
        "bin/pcl_pcd2ply",
    )

    JLLWrappers.@init_executable_product(
        pcl_pcd2vtk,
        "bin/pcl_pcd2vtk",
    )

    JLLWrappers.@init_executable_product(
        pcl_pcd_change_viewpoint,
        "bin/pcl_pcd_change_viewpoint",
    )

    JLLWrappers.@init_executable_product(
        pcl_pcd_convert_NaN_nan,
        "bin/pcl_pcd_convert_NaN_nan",
    )

    JLLWrappers.@init_executable_product(
        pcl_pcd_introduce_nan,
        "bin/pcl_pcd_introduce_nan",
    )

    JLLWrappers.@init_executable_product(
        pcl_pclzf2pcd,
        "bin/pcl_pclzf2pcd",
    )

    JLLWrappers.@init_executable_product(
        pcl_plane_projection,
        "bin/pcl_plane_projection",
    )

    JLLWrappers.@init_executable_product(
        pcl_ply2obj,
        "bin/pcl_ply2obj",
    )

    JLLWrappers.@init_executable_product(
        pcl_ply2pcd,
        "bin/pcl_ply2pcd",
    )

    JLLWrappers.@init_executable_product(
        pcl_ply2ply,
        "bin/pcl_ply2ply",
    )

    JLLWrappers.@init_executable_product(
        pcl_ply2raw,
        "bin/pcl_ply2raw",
    )

    JLLWrappers.@init_executable_product(
        pcl_plyheader,
        "bin/pcl_plyheader",
    )

    JLLWrappers.@init_executable_product(
        pcl_poisson_reconstruction,
        "bin/pcl_poisson_reconstruction",
    )

    JLLWrappers.@init_executable_product(
        pcl_progressive_morphological_filter,
        "bin/pcl_progressive_morphological_filter",
    )

    JLLWrappers.@init_executable_product(
        pcl_radius_filter,
        "bin/pcl_radius_filter",
    )

    JLLWrappers.@init_executable_product(
        pcl_sac_segmentation_plane,
        "bin/pcl_sac_segmentation_plane",
    )

    JLLWrappers.@init_executable_product(
        pcl_spin_estimation,
        "bin/pcl_spin_estimation",
    )

    JLLWrappers.@init_executable_product(
        pcl_train_linemod_template,
        "bin/pcl_train_linemod_template",
    )

    JLLWrappers.@init_executable_product(
        pcl_train_unary_classifier,
        "bin/pcl_train_unary_classifier",
    )

    JLLWrappers.@init_executable_product(
        pcl_transform_from_viewpoint,
        "bin/pcl_transform_from_viewpoint",
    )

    JLLWrappers.@init_executable_product(
        pcl_transform_point_cloud,
        "bin/pcl_transform_point_cloud",
    )

    JLLWrappers.@init_executable_product(
        pcl_unary_classifier_segment,
        "bin/pcl_unary_classifier_segment",
    )

    JLLWrappers.@init_executable_product(
        pcl_uniform_sampling,
        "bin/pcl_uniform_sampling",
    )

    JLLWrappers.@init_executable_product(
        pcl_vfh_estimation,
        "bin/pcl_vfh_estimation",
    )

    JLLWrappers.@init_executable_product(
        pcl_voxel_grid,
        "bin/pcl_voxel_grid",
    )

    JLLWrappers.@init_executable_product(
        pcl_xyz2pcd,
        "bin/pcl_xyz2pcd",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
